import type { InsightCard, MediaAsset, SettingsState, TimelineEvent } from "@/lib/types"

export const mediaAssets: MediaAsset[] = [
  {
    id: "a1",
    name: "founder-note-2026-02-14.m4a",
    type: "audio",
    durationLabel: "58m",
    status: "processing",
  },
  {
    id: "v1",
    name: "tiktok-ux-ritual.mp4",
    type: "video",
    durationLabel: "04m 38s",
    status: "queued",
  },
  {
    id: "i1",
    name: "obsidian-board-screenshot.heif",
    type: "image",
    durationLabel: "single frame",
    status: "completed",
  },
]

export const insightCards: InsightCard[] = [
  {
    id: "c1",
    title: "Recurring Thinking Motifs",
    category: "Cognitive Pattern",
    color: "violet",
    points: [
      "Daily systems over sporadic motivation.",
      "Preference for visual progress signaling.",
      "High tolerance for complexity if structure exists.",
    ],
  },
  {
    id: "c2",
    title: "Strategic Keywords",
    category: "Semantic Signals",
    color: "magenta",
    points: [
      "knowledge graph",
      "retrieval rhythm",
      "memory refinery",
      "decision traceability",
    ],
  },
  {
    id: "c3",
    title: "Actionable Insight",
    category: "Execution Trigger",
    color: "teal",
    points: [
      "Split content ingestion into 12-minute chunks.",
      "Promote recurring nouns into permanent evergreen notes.",
      "Auto-link to daily notes and concept hubs.",
    ],
  },
  {
    id: "c4",
    title: "Knowledge Risks",
    category: "Quality Gate",
    color: "lime",
    points: [
      "Potential hallucination in quoted references.",
      "Audio diarization uncertainty around guest speaker moments.",
      "Low confidence in one blurred screenshot caption.",
    ],
  },
]

export const timelineEvents: TimelineEvent[] = [
  {
    id: "t1",
    at: "18:03",
    title: "Audio transcribed",
    description: "Gemini file processing completed and transcript normalized.",
  },
  {
    id: "t2",
    at: "18:06",
    title: "Insights extracted",
    description: "22 key points, 16 keywords, 5 thought threads generated.",
  },
  {
    id: "t3",
    at: "18:09",
    title: "Note preview ready",
    description: "Markdown compiled with links to concept and daily notes.",
  },
]

export const defaultSettings: SettingsState = {
  vaultPath: "C:\\Users\\israel.toledo\\AppData\\Local\\Obsidian\\Israel's Vault",
  obsidianCliPath: "obsidian",
  geminiModel: "gemini-2.5-flash",
  writeMode: "cli_fallback",
}

export const notePreview = `---
title: "[AI Capture] Founder note + TikTok concept synthesis"
tags: [ai-capture, insight, knowledge-graph, obsidian-agent]
source_files:
  - founder-note-2026-02-14.m4a
  - tiktok-ux-ritual.mp4
  - obsidian-board-screenshot.heif
---

## Executive Summary
The captured materials converge on one strategic direction: transform fragmented daily media into a persistent knowledge lattice anchored by low-friction capture and high-fidelity linking.

## Key Insights
- Momentum is generated by visible progress, not hidden processing.
- The user prefers graph-like navigation over folder-only organization.
- Short-form video ideas can seed long-form evergreen notes when normalized early.

## Keywords
knowledge graph, memory refinery, retrieval rhythm, insight compression

## Suggested Links
- [[Daily/2026-02-14]]
- [[Concepts/Knowledge Graph]]
- [[Concepts/Execution Systems]]

## Next Actions
1. Create a permanent note for "memory refinery".
2. Append these insights to today's daily note.
3. Schedule tomorrow's ingestion review block.
`
